Improvements to Bash scripts, removal of unneeded files

diff --git a/src/RunTBABM b/src/RunTBABM
--- a/src/RunTBABM
+++ b/src/RunTBABM
@@ -1,4 +1,4 @@
-#!/bin/sh           
+#!/usr/bin/env bash
 
 # Print usage information
 function print_usage {
@@ -11,6 +11,7 @@ function print_usage {
   echo "Options:"
   echo "  -b name       Name of the run"
   echo "  -e address    Email when job is finished. Implies -q"
+  echo "  -c file       Collated. Each line of 'file' is a RunSheet"
   # echo "  -g            Graph the output"
   echo "  -i init_size  Initial size of population. Default 31000"
   echo "  -q            Run as a batch job through sbatch"
@@ -22,7 +23,7 @@ function print_usage {
 # See documentation of 'getopts' or 
 # https://sookocheff.com/post/bash/parsing-bash-script-arguments-with-shopts/
 # for more information about processing CLI arguments in Bash scripts
-optstring=":hb:r:n:t:qe:i:gm:j:"
+optstring=":hb:r:n:t:qc:e:i:gm:j:"
 
 # Make sure at least one argument was supplied. $# is the number of arguments
 # to the script.
@@ -38,6 +39,8 @@ N_TRAJECTORIES=4
 N_THREADS=1
 N_JOBS=2
 N_INDIVIDUALS=31000
+COLLATED=false
+COLLATED_FILE=""
 DO_BATCH=false
 DO_EMAIL=false
 DO_GRAPH=false
@@ -48,6 +51,10 @@ RUNTBABM_OPTSTRING=""
 # Put the flag being processed into the variable $opt
 while getopts $optstring opt; do
   case ${opt} in
+    c )
+      COLLATED=true; COLLATED_FILE=$OPTARG
+      RUNTBABM_OPTSTRING+="-c $OPTARG "
+      ;;
     h )
       print_usage; exit 0
       ;;
@@ -96,12 +103,12 @@ while getopts $optstring opt; do
   esac
 done
 
-if [[ "$RANGEFILE" = "" ]]; then
+if [[ "$RANGEFILE" = "" && "$COLLATE" = "false" ]]; then
   echo "Error: Must specify rangefile" 1>&2
   exit 1;
 fi
 
-if [[ "$N_RUNSHEETS" = 0 ]]; then
+if [[ "$N_RUNSHEETS" = "0" && "$COLLATE" = "false" ]]; then
   echo "Error: Must specify # rangefiles" 1>&2
   exit 1;
 fi
@@ -146,22 +153,26 @@ which parallel > /dev/null || \
   { (>&2 echo '"parallel" not found in $PATH; exiting'); exit $E_RUNERR; };
 
 # Make sure that all of the RunSheets exist
-if ! seq -w $N_RUNSHEETS | parallel -X stat {}.json > /dev/null; then
-  echo "Could not stat 1 or more of the runsheets; exiting";
-  exit 1;
+if [[ "$COLLATE" = "false" ]]; then
+  if ! seq -w $N_RUNSHEETS | parallel -X stat {}.json > /dev/null; then
+    echo "Could not stat 1 or more of the runsheets; exiting";
+    exit 1;
+  fi
 fi
 
 srun="";
 if which 'srun' > /dev/null; then
   # This specifies the options used to run srun. The "-N1 -n1" options are
   # used to allocates a single core to each task.
-  srun="srun -n1 -N1 --cpus-per-task $N_THREADS --exclusive";
+  srun="srun -n1 --cpus-per-task $N_THREADS --exclusive";
 fi
 
-seq -w $N_RUNSHEETS | xargs rm -rf || \
-  { (>&2 echo "Failed to remove existing result directories; exiting"); exit $?; }
-seq -w $N_RUNSHEETS | xargs mkdir || \
-  { (>&2 echo "Creation of an output directory failed; exiting"); exit $?; }
+if [[ "$COLLATE" = "false" ]]; then
+  seq -w $N_RUNSHEETS | xargs rm -rf || \
+    { (>&2 echo "Failed to remove existing result directories; exiting"); exit $?; }
+  seq -w $N_RUNSHEETS | xargs mkdir || \
+    { (>&2 echo "Creation of an output directory failed; exiting"); exit $?; }
+fi
 
 # Determine which TBABM binary will be used. Any TBABM binary in the working
 # directory is chosen first. Then, if Lmod is available, an attempt is made 
@@ -172,35 +183,18 @@ else
   TBABM_BIN="TBABM"
 fi
 
-# # Check to see if Lmod exists
-# elif module help > /dev/null 2>&1; then
-#   module load TBABM || { (>&2 echo 'Loading TBABM from Lmod failed; exiting');\
-#                     exit $E_RUNERR; };
-
-#   which -s TBABM || \
-#     { (>&2 echo 'No TBABM found in $PATH after successful Lmod load; exiting');\
-#            exit $E_RUNERR; };
-
-#   TBABM_BIN=`which TBABM`;
-#   echo "Binary found [Lmod]: $(which TBABM)";
-
-# else
-#   which TBABM > /dev/null 2>&1 || \
-#     { (>&2 echo 'No Lmod, TBABM in $PATH, or TBABM in ./; exiting');\
-#            exit $E_RUNERR; };
-
-#   TBABM_BIN=`which TBABM`;
-#   echo "Binary found: [path]: $(which TBABM)";
-# fi
-
 # Build the string of options passed to the TBABM binary. Escape (using '') 
 # variables whose values should be resolved on binary invocation.
 TBABM_OPTSTRING=""
 TBABM_OPTSTRING+="-t $N_TRAJECTORIES "
 TBABM_OPTSTRING+="-n $N_INDIVIDUALS "
-TBABM_OPTSTRING+='-p {}.json '
+if [[ "$COLLATE" = "false" ]]; then
+  TBABM_OPTSTRING+='-p {}.json '
+else
+  TBABM_OPTSTRING+='-p {} '
+fi
 TBABM_OPTSTRING+='-s $RANDOM '
-TBABM_OPTSTRING+='-o {}/ '
+TBABM_OPTSTRING+='-o {#}/ '
 TBABM_OPTSTRING+="-m $N_THREADS "
 TBABM_OPTSTRING+='-h household_structure.csv'
 
@@ -216,8 +210,41 @@ tbabm="$TBABM_BIN $TBABM_OPTSTRING"
 #   The combination of --joblog and --resume create a task log that
 #   can be used to monitor progress.
 #
-parallel="parallel -j $N_JOBS --delay 0.2 --joblog parallel.log"
+ps_opts="-j $N_JOBS --delay 0.2 --joblog parallel.log"
+pc_opts="$ps_opts --pipe --cat -N1"
 
-seq -w $N_RUNSHEETS | $parallel $srun $tbabm '>' {}.log '2>&1;' echo {}
+function tbabm_coll () {
+  mkdir $2
+
+  TBABM_OPTS="-t $N_TRAJECTORIES -n $N_INDIVIDUALS -p $1 -s $RANDOM -o $2/ -m $N_THREADS -h household_structure.csv"
+
+  $srun $TBABM_BIN $TBABM_OPTS > $2/stdout.txt 2> $2/stderr.txt
+
+  echo $2
+}
+export N_TRAJECTORIES N_INDIVIDUALS N_THREADS srun TBABM_BIN
+export -f tbabm_coll
+
+function analyze () {
+  ../src/summary_statistics.sh $1 >> results.csv # | tee -a results.csv 1>&2
+  echo $1
+}
+export -f analyze
+
+function remove () {
+  rm -rf $1
+}
+export -f remove
+
+if [[ "$COLLATE" = "false" ]]; then
+  seq -w $N_RUNSHEETS | parallel $ps_opts $srun $tbabm '>' {}.log '2>&1;' echo {}
+else
+  cat $COLLATED_FILE | 
+    parallel $pc_opts tbabm_coll {} {#} |
+    # parallel -j1 analyze |
+    ./pipes.R |
+    parallel -j1 remove # &&
+  # ./likelihoods.R < results.csv
+fi
 
 exit $?;
